// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCSqCIqawRQEFjy2azRyYl-5mXI2PkJiVM",
    authDomain: "facebook-clone-9ec01.firebaseapp.com",
    projectId: "facebook-clone-9ec01",
    storageBucket: "facebook-clone-9ec01.appspot.com",
    messagingSenderId: "672802209610",
    appId: "1:672802209610:web:fd49224d70b91112758bb3",
    measurementId: "G-TYVJWVV6C1",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqCIqawRQEFjy2azRyYl-5mXI2PkJiVM',
    appId: '1:672802209610:android:a3a6765f58fb5414758bb3',
    messagingSenderId: '672802209610',
    projectId: 'facebook-clone-9ec01',
    storageBucket: 'facebook-clone-9ec01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSqCIqawRQEFjy2azRyYl-5mXI2PkJiVM',
    appId: '1:672802209610:ios:68edd8f42f8253ef758bb3',
    messagingSenderId: '672802209610',
    projectId: 'facebook-clone-9ec01',
    storageBucket: 'facebook-clone-9ec01.appspot.com',
    iosClientId:
        '672802209610-ets1k1ad356qffmrgmklsv1e3n6gbv4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookClone',
  );
}
